In [ ]:
#https://www.kaggle.com/philculliton/nlp-getting-started-tutorial/notebook

In [139]:
import numpy as np

In [140]:
import pandas as pd

In [141]:

from sklearn import feature_extraction, linear_model, model_selection, preprocessing


In [142]:
train=pd.read_csv("train.csv")
test=pd.read_csv("test.csv")

In [143]:
train.shape

(7613, 5)

In [144]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7613 entries, 0 to 7612
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   id        7613 non-null   int64 
 1   keyword   7552 non-null   object
 2   location  5080 non-null   object
 3   text      7613 non-null   object
 4   target    7613 non-null   int64 
dtypes: int64(2), object(3)
memory usage: 297.5+ KB


In [145]:
test.shape

(3263, 4)

In [146]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3263 entries, 0 to 3262
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   id        3263 non-null   int64 
 1   keyword   3237 non-null   object
 2   location  2158 non-null   object
 3   text      3263 non-null   object
dtypes: int64(1), object(3)
memory usage: 102.1+ KB


In [147]:
train.head()

id keyword location                                               text  \
0   1     NaN      NaN  Our Deeds are the Reason of this #earthquake M...   
1   4     NaN      NaN             Forest fire near La Ronge Sask. Canada   
2   5     NaN      NaN  All residents asked to 'shelter in place' are ...   
3   6     NaN      NaN  13,000 people receive #wildfires evacuation or...   
4   7     NaN      NaN  Just got sent this photo from Ruby #Alaska as ...   

   target  
0       1  
1       1  
2       1  
3       1  
4       1

In [148]:
test.head()

id keyword location                                               text
0   0     NaN      NaN                 Just happened a terrible car crash
1   2     NaN      NaN  Heard about #earthquake is different cities, s...
2   3     NaN      NaN  there is a forest fire at spot pond, geese are...
3   9     NaN      NaN           Apocalypse lighting. #Spokane #wildfires
4  11     NaN      NaN      Typhoon Soudelor kills 28 in China and Taiwan

In [149]:
train.isnull().sum()

id             0
keyword       61
location    2533
text           0
target         0
dtype: int64

In [150]:
test.isnull().sum()

id             0
keyword       26
location    1105
text           0
dtype: int64

In [151]:
train[train["target"]==0] ["text"].values[0] #first tweet in dataset that is not about disaster

"What's up man?"

In [152]:
train[train["target"]==1] ["text"].values[0] ##first tweet in dataset that is about disaster

'Our Deeds are the Reason of this #earthquake May ALLAH Forgive us all'

# count vectorization
example_train_vectors = count_vectorizer.fit_transform(train_df["text"][0:5])
## we use .todense() here because these vectors are "sparse" (only non-zero elements are kept to save space)
print(example_train_vectors[0].todense().shape)

print(example_train_vectors[0].todense())

output:
(1, 54)

[[0 0 0 1 1 1 0 0 0 0 0 0 1 1 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 1 0
  0 0 0 1 0 0 0 0 0 0 0 0 0 1 1 0 1 0]]
  
  The above tells us that:

There are 54 unique words (or "tokens") in the first five tweets.
The first tweet contains only some of those unique tokens - all of the non-zero counts above are the tokens that DO exist in the first tweet.
Now let's create vectors for all of our tweets.

In [156]:
count_vec=feature_extraction.text.CountVectorizer()
#(analyzer='word',token_pattern=r'\w+', ngram_range=(1, 3), stop_words = 'english') #token_pattern=r'\w{1,}

In [157]:
train_count=count_vec.fit_transform(train['text']) #-vectorizer_to_machine-readable
train_count.shape #same column as test_count

(7613, 21637)

In [158]:
test_count=count_vec.transform(test['text'])
test_count.shape ##same column as train_count

(3263, 21637)

# classifier

In [121]:
clf=linear_model.RidgeClassifier()


In [122]:
clf.fit(train_count, train["target"])


RidgeClassifier()

In [125]:
scores = model_selection.cross_val_score(clf, train_count, train["target"], cv=3, scoring="accuracy")
scores


array([0.70173365, 0.67533491, 0.71344107])

In [124]:
train['target'].dtype

dtype('int64')

In [159]:
from sklearn.svm import SVC
clf1=SVC()

In [160]:
clf1.fit(train_count, train["target"])


SVC()

In [161]:
scores = model_selection.cross_val_score(clf1, train_count, train["target"], cv=3, scoring="accuracy")
scores

array([0.74704492, 0.71237195, 0.76271186])

In [162]:
from sklearn.naive_bayes import MultinomialNB
clf2= MultinomialNB()

In [163]:
clf2.fit(train_count, train["target"])


MultinomialNB()

In [164]:
scores = model_selection.cross_val_score(clf2, train_count, train["target"], cv=3, scoring="accuracy")
scores

array([0.72813239, 0.70055162, 0.74615688])

# submission

In [77]:
sample_submission = pd.read_csv('sample_submission.csv')


In [78]:
sample_submission["target"] = clf.predict(test_count)
sample_submission["target"] = clf1.predict(test_count)

In [79]:
sample_submission.head()

id  target
0   0       0
1   2       0
2   3       1
3   9       0
4  11       1

In [69]:
sample_submission.to_csv("submission.csv", index=False)

In [80]:
sample_submission.to_csv("submission1.csv", index=False)